title: LACMIP Digital Data Management
description: Documentation and workflows related to digitization of the invertebrate paleontology collections.
baseurl: /lacmip
logo: assets/img/lacmip-logo.jpg

collections:
  documentation:
    output: true
  workflows:
    output: true

defaults:
  - scope:
      path: ""
      type: "documentation"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "workflows"
    values:
      layout: "default"
