title: EMu Handbook
description: Documentation and workflows related to digitization of the LACMIP invertebrate paleontology collections.
baseurl: /lacmip
logo: assets/img/lacmip-logo.jpg
theme: jekyll-theme-minimal
# google_analytics:

collections:
  documentation:
    output: true

defaults:
  - scope:
      path: ""
      type: "documentation"
    values:
      layout: "default"
